#ifndef EEZ_LVGL_UI_VARS_H
#define EEZ_LVGL_UI_VARS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// enum declarations



// Flow global variables

enum FlowGlobalVariables {
    FLOW_GLOBAL_VARIABLE_IS_WI_FI_AP = 0,
    FLOW_GLOBAL_VARIABLE_IS_HEADER = 1,
    FLOW_GLOBAL_VARIABLE_ISINPUT_TEXT = 2,
    FLOW_GLOBAL_VARIABLE_HH_MM = 3,
    FLOW_GLOBAL_VARIABLE_CURRENT_DATE = 4,
    FLOW_GLOBAL_VARIABLE_NOTIF_WI_FI = 5,
    FLOW_GLOBAL_VARIABLE_IS_WIFI = 6,
    FLOW_GLOBAL_VARIABLE_TIME_INFO_ARRAY = 7,
    FLOW_GLOBAL_VARIABLE_SAVE_TIME = 8,
    FLOW_GLOBAL_VARIABLE_IS_CHARGE = 9,
    FLOW_GLOBAL_VARIABLE_BT = 10,
    FLOW_GLOBAL_VARIABLE_HIDDERALARM = 11,
    FLOW_GLOBAL_VARIABLE_FOOTSTEP = 12,
    FLOW_GLOBAL_VARIABLE_ISSTEP = 13,
    FLOW_GLOBAL_VARIABLE_NAMA = 14,
    FLOW_GLOBAL_VARIABLE_USIA = 15,
    FLOW_GLOBAL_VARIABLE_BB = 16,
    FLOW_GLOBAL_VARIABLE_IS_COUNTER = 17,
    FLOW_GLOBAL_VARIABLE_SAVE_ALARM = 18,
    FLOW_GLOBAL_VARIABLE_H = 19,
    FLOW_GLOBAL_VARIABLE_PLAY_ALARM = 20,
    FLOW_GLOBAL_VARIABLE_FILE_AUDIO = 21,
    FLOW_GLOBAL_VARIABLE_START_TIME = 22,
    FLOW_GLOBAL_VARIABLE_END = 23,
    FLOW_GLOBAL_VARIABLE_END_TIME = 24,
    FLOW_GLOBAL_VARIABLE_AUDIO_SELESTED = 25,
    FLOW_GLOBAL_VARIABLE_PLAY_AUDIO = 26,
    FLOW_GLOBAL_VARIABLE_SET_ALARAM = 27,
    FLOW_GLOBAL_VARIABLE_IS_CALCULATE = 28,
    FLOW_GLOBAL_VARIABLE_HASIL_HITUNG = 29,
    FLOW_GLOBAL_VARIABLE_CAIRAN = 30,
    FLOW_GLOBAL_VARIABLE_CLOSE_POPUP = 31,
    FLOW_GLOBAL_VARIABLE_PLAY_ALARM2 = 32,
    FLOW_GLOBAL_VARIABLE_PLAY_ALARM3 = 33,
    FLOW_GLOBAL_VARIABLE_ALARMKE = 34,
    FLOW_GLOBAL_VARIABLE_HIDDENALARM2 = 35,
    FLOW_GLOBAL_VARIABLE_HIDDENALARM3 = 36,
    FLOW_GLOBAL_VARIABLE_START_TIME2 = 37,
    FLOW_GLOBAL_VARIABLE_START_TIME3 = 38,
    FLOW_GLOBAL_VARIABLE_END_TIME2 = 39,
    FLOW_GLOBAL_VARIABLE_END_TIME3 = 40,
    FLOW_GLOBAL_VARIABLE_HIDDENPLUS = 41,
    FLOW_GLOBAL_VARIABLE_CAIRAN_TOTAL = 42,
    FLOW_GLOBAL_VARIABLE_IS_HUMIDITY = 43,
    FLOW_GLOBAL_VARIABLE_SSID_STA = 44,
    FLOW_GLOBAL_VARIABLE_PASSS_STA = 45,
    FLOW_GLOBAL_VARIABLE_SAVE_WIFI_STA = 46,
    FLOW_GLOBAL_VARIABLE_SSID_AP = 47,
    FLOW_GLOBAL_VARIABLE_PASS_AP = 48,
    FLOW_GLOBAL_VARIABLE_SAVE_WIFI_AP = 49
};

// Native global variables



#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_VARS_H*/