#ifndef EEZ_LVGL_UI_VARS_H
#define EEZ_LVGL_UI_VARS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// enum declarations



// Flow global variables

enum FlowGlobalVariables {
    FLOW_GLOBAL_VARIABLE_IS_WI_FI_AP = 0,
    FLOW_GLOBAL_VARIABLE_IS_HEADER = 1,
    FLOW_GLOBAL_VARIABLE_HH_MM = 2,
    FLOW_GLOBAL_VARIABLE_CURRENT_DATE = 3,
    FLOW_GLOBAL_VARIABLE_NOTIF_WI_FI = 4,
    FLOW_GLOBAL_VARIABLE_IS_WIFI = 5,
    FLOW_GLOBAL_VARIABLE_TIME_INFO_ARRAY = 6,
    FLOW_GLOBAL_VARIABLE_SAVE_TIME = 7,
    FLOW_GLOBAL_VARIABLE_IS_CHARGE = 8,
    FLOW_GLOBAL_VARIABLE_BT = 9,
    FLOW_GLOBAL_VARIABLE_HIDDERALARM = 10,
    FLOW_GLOBAL_VARIABLE_FOOTSTEP = 11,
    FLOW_GLOBAL_VARIABLE_ISSTEP = 12,
    FLOW_GLOBAL_VARIABLE_NAMA = 13,
    FLOW_GLOBAL_VARIABLE_USIA = 14,
    FLOW_GLOBAL_VARIABLE_BB = 15,
    FLOW_GLOBAL_VARIABLE_IS_COUNTER = 16,
    FLOW_GLOBAL_VARIABLE_SAVE_ALARM = 17,
    FLOW_GLOBAL_VARIABLE_H = 18,
    FLOW_GLOBAL_VARIABLE_PLAY_ALARM = 19,
    FLOW_GLOBAL_VARIABLE_FILE_AUDIO = 20,
    FLOW_GLOBAL_VARIABLE_START_TIME = 21,
    FLOW_GLOBAL_VARIABLE_END = 22,
    FLOW_GLOBAL_VARIABLE_END_TIME = 23,
    FLOW_GLOBAL_VARIABLE_AUDIO_SELESTED = 24,
    FLOW_GLOBAL_VARIABLE_PLAY_AUDIO = 25,
    FLOW_GLOBAL_VARIABLE_SET_ALARAM = 26,
    FLOW_GLOBAL_VARIABLE_IS_CALCULATE = 27,
    FLOW_GLOBAL_VARIABLE_HASIL_HITUNG = 28
};

// Native global variables



#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_VARS_H*/