; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:waveshare-esp32-s3-touch-amoled-1-8]
platform = espressif32
board = waveshare-esp32-s3-touch-amoled-1-8
framework = arduino

board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.f_flash = 80000000L

; Force PSRAM detection
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM=1

lib_deps =
  bblanchon/ArduinoJson @ ^7.4.2
  lewisxhe/XPowersLib @ ^0.2.0
  bbx10/DNSServer@^1.1.0
  ; lovyan03/LovyanGFX@^1.1.16
  ; ArduinoJson@7.0.0
  ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer

lib_ignore = WiFiNINA

build_flags =
  -w
  -D LV_CONF_INCLUDE_SIMPLE
  -I include
  -I lib/lvgl/src
  -D LV_LVGL_H_INCLUDE_SIMPLE
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM=1                        
  -mfix-esp32-psram-cache-issue
  -DXPOWERS_CHIP_AXP2101

monitor_speed = 115200